
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.chinaredstar.product.dubbo.sap.goods.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-08-21T15:21:37.766+08:00
 * Generated source version: 3.1.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_ZMM_MATERIAL_DATA_REQService",
                      portName = "HTTPS_Port",
                      targetNamespace = "http://chinaredstar.com/ecc2zt",
                      wsdlLocation = "file:/D:/work/proj/future-mmall/ws-client/sap08.wsdl",
                      endpointInterface = "com.chinaredstar.product.dubbo.service.sap08.SIZMMMATERIALDATAREQ")
                      
public class HTTPS_PortImpl implements SIZMMMATERIALDATAREQ {

    private static final Logger LOG = Logger.getLogger(HTTPS_PortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.chinaredstar.product.dubbo.service.sap08.SIZMMMATERIALDATAREQ#siZMMMATERIALDATAREQ(com.sap.document.sap.rfc.functions.ZMMMATERIALDATA parameters)*
     */
    public com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATAResponse siZMMMATERIALDATAREQ(com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA parameters) { 
        LOG.info("Executing operation siZMMMATERIALDATAREQ");
        System.out.println(parameters);
        try {
            com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATAResponse _return = new com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATAResponse();
            _return.setOTMESSAG("OTMESSAG-906685143");
            _return.setOTSUBRC("OTSUBRC-567386523");
            com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATAResponse.ETDATA _returnETDATA = new com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATAResponse.ETDATA();
            java.util.List<com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA2> _returnETDATAItem = new java.util.ArrayList<com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA2>();
            com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA2 _returnETDATAItemVal1 = new com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA2();
            _returnETDATAItemVal1.setMTART("MTART164879730");
            _returnETDATAItemVal1.setMATNR("MATNR-33841137");
            _returnETDATAItemVal1.setMAKTX("MAKTX-1207834294");
            _returnETDATAItemVal1.setMATKL("MATKL-926390494");
            _returnETDATAItemVal1.setWGBEZ("WGBEZ-1309528517");
            _returnETDATAItemVal1.setMEINS("MEINS-258084454");
            _returnETDATAItemVal1.setBRGEW(new java.math.BigDecimal("-21344381629944532.9195994926238866210"));
            _returnETDATAItemVal1.setNTGEW(new java.math.BigDecimal("5130929075532086276.1342476158583624456"));
            _returnETDATAItemVal1.setGEWEI("GEWEI1825875976");
            _returnETDATAItemVal1.setVOLUM(new java.math.BigDecimal("6381494074447951812.8987805480656207444"));
            _returnETDATAItemVal1.setVOLEH("VOLEH-1712524634");
            _returnETDATAItemVal1.setORIGIN("ORIGIN-976551548");
            _returnETDATAItemVal1.setMODEL("MODEL-722312976");
            _returnETDATAItemVal1.setNORMS("NORMS-544103539");
            _returnETDATAItemVal1.setNATURE("NATURE-1173360006");
            _returnETDATAItemVal1.setPRODMA("PRODMA-958467145");
            _returnETDATAItemVal1.setBRAND("BRAND-852900165");
            _returnETDATAItemVal1.setSERIES("SERIES1853698591");
            _returnETDATAItemVal1.setCOLOUR("COLOUR1858017558");
            _returnETDATAItemVal1.setLIFNR("LIFNR1417918768");
            _returnETDATAItem.add(_returnETDATAItemVal1);
            _returnETDATA.getItem().addAll(_returnETDATAItem);
            _return.setETDATA(_returnETDATA);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
