
package com.chinaredstar.product.dubbo.sap.goods.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-08-21T15:21:37.752+08:00
 * Generated source version: 3.1.16
 * 
 */
public final class SIZMMMATERIALDATAREQ_HTTPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://chinaredstar.com/ecc2zt", "SI_ZMM_MATERIAL_DATA_REQService");

    private SIZMMMATERIALDATAREQ_HTTPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIZMMMATERIALDATAREQService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIZMMMATERIALDATAREQService ss = new SIZMMMATERIALDATAREQService(wsdlURL, SERVICE_NAME);
        SIZMMMATERIALDATAREQ port = ss.getHTTPPort();  

        BindingProvider bp = (BindingProvider) port;
        Map<String, Object> map = bp.getRequestContext();
        map.put(BindingProvider.USERNAME_PROPERTY, "zhaijc");
        map.put(BindingProvider.PASSWORD_PROPERTY, "huaxia06");
        
        {
        System.out.println("Invoking siZMMMATERIALDATAREQ...");
        com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA _siZMMMATERIALDATAREQ_parameters = new com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA();
        _siZMMMATERIALDATAREQ_parameters.setINDATE("20180821");
//        _siZMMMATERIALDATAREQ_parameters.setINMATNR("INMATNR-1111271183");
        _siZMMMATERIALDATAREQ_parameters.setINMATNR("");
        com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA.ETDATA _siZMMMATERIALDATAREQ_parametersETDATA = new com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA.ETDATA();
        /*
        java.util.List<com.sap.document.sap.rfc.functions.ZMMMATERIALDATA2> _siZMMMATERIALDATAREQ_parametersETDATAItem = new java.util.ArrayList<com.sap.document.sap.rfc.functions.ZMMMATERIALDATA2>();
        com.sap.document.sap.rfc.functions.ZMMMATERIALDATA2 _siZMMMATERIALDATAREQ_parametersETDATAItemVal1 = new com.sap.document.sap.rfc.functions.ZMMMATERIALDATA2();
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMTART("MTART-888109765");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMATNR("MATNR357425097");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMAKTX("MAKTX-1195578682");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMATKL("MATKL-1107514750");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setWGBEZ("WGBEZ1394786437");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMEINS("MEINS-767787523");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setBRGEW(new java.math.BigDecimal("6819639551375029933.213793654286629854"));
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setNTGEW(new java.math.BigDecimal("3739816314718577003.4751494738740011801"));
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setGEWEI("GEWEI-925863051");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setVOLUM(new java.math.BigDecimal("4313471730777667601.21679870940642252"));
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setVOLEH("VOLEH1114057454");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setORIGIN("ORIGIN-555647144");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMODEL("MODEL-1209380361");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setNORMS("NORMS-885818218");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setNATURE("NATURE-83341088");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setPRODMA("PRODMA-366204703");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setBRAND("BRAND411752512");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setSERIES("SERIES1391140742");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setCOLOUR("COLOUR1190861704");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setLIFNR("LIFNR-323794764");
        _siZMMMATERIALDATAREQ_parametersETDATAItem.add(_siZMMMATERIALDATAREQ_parametersETDATAItemVal1);
        _siZMMMATERIALDATAREQ_parametersETDATA.getItem().addAll(_siZMMMATERIALDATAREQ_parametersETDATAItem);
        _siZMMMATERIALDATAREQ_parameters.setETDATA(_siZMMMATERIALDATAREQ_parametersETDATA);
        */
        _siZMMMATERIALDATAREQ_parameters.setETDATA(_siZMMMATERIALDATAREQ_parametersETDATA);
        com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATAResponse _siZMMMATERIALDATAREQ__return = port.siZMMMATERIALDATAREQ(_siZMMMATERIALDATAREQ_parameters);
        System.out.println("siZMMMATERIALDATAREQ.result=" + _siZMMMATERIALDATAREQ__return);


        }

        System.exit(0);
    }

}
