package com.chinaredstar.product.dubbo.sap.goods.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-08-21T15:21:37.793+08:00
 * Generated source version: 3.1.16
 * 
 */
@WebService(targetNamespace = "http://chinaredstar.com/ecc2zt", name = "SI_ZMM_MATERIAL_DATA_REQ")
@XmlSeeAlso({com.chinaredstar.product.dubbo.sap.goods.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIZMMMATERIALDATAREQ {

    @WebMethod(operationName = "SI_ZMM_MATERIAL_DATA_REQ", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ZMM_MATERIAL_DATA.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATAResponse siZMMMATERIALDATAREQ(
        @WebParam(partName = "parameters", name = "ZMM_MATERIAL_DATA", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
        com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA parameters
    );
}
