
package com.chinaredstar.product.dubbo.sap.goods.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-08-21T15:21:37.686+08:00
 * Generated source version: 3.1.16
 * 
 */
public final class SIZMMMATERIALDATAREQ_HTTPSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://chinaredstar.com/ecc2zt", "SI_ZMM_MATERIAL_DATA_REQService");

    private SIZMMMATERIALDATAREQ_HTTPSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIZMMMATERIALDATAREQService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIZMMMATERIALDATAREQService ss = new SIZMMMATERIALDATAREQService(wsdlURL, SERVICE_NAME);
        SIZMMMATERIALDATAREQ port = ss.getHTTPSPort();  
        
        {
        System.out.println("Invoking siZMMMATERIALDATAREQ...");
        com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA _siZMMMATERIALDATAREQ_parameters = new com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA();
        _siZMMMATERIALDATAREQ_parameters.setINDATE("INDATE-1812996187");
        _siZMMMATERIALDATAREQ_parameters.setINMATNR("INMATNR-837634573");
        com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA.ETDATA _siZMMMATERIALDATAREQ_parametersETDATA = new com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA.ETDATA();
        java.util.List<com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA2> _siZMMMATERIALDATAREQ_parametersETDATAItem = new java.util.ArrayList<com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA2>();
        com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA2 _siZMMMATERIALDATAREQ_parametersETDATAItemVal1 = new com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATA2();
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMTART("MTART-1361479871");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMATNR("MATNR-96020870");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMAKTX("MAKTX-2019559634");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMATKL("MATKL-872556841");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setWGBEZ("WGBEZ-1782825817");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMEINS("MEINS665099931");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setBRGEW(new java.math.BigDecimal("-4630754115615062317.2281072320355712742"));
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setNTGEW(new java.math.BigDecimal("4058908473308084270.4750456609733354443"));
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setGEWEI("GEWEI-1993631759");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setVOLUM(new java.math.BigDecimal("-2532415556747813242.7576690047529535520"));
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setVOLEH("VOLEH710004411");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setORIGIN("ORIGIN483055736");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setMODEL("MODEL854324250");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setNORMS("NORMS-1150272684");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setNATURE("NATURE-1159201296");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setPRODMA("PRODMA-926198174");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setBRAND("BRAND-164470892");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setSERIES("SERIES640883643");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setCOLOUR("COLOUR2066415285");
        _siZMMMATERIALDATAREQ_parametersETDATAItemVal1.setLIFNR("LIFNR-324977739");
        _siZMMMATERIALDATAREQ_parametersETDATAItem.add(_siZMMMATERIALDATAREQ_parametersETDATAItemVal1);
        _siZMMMATERIALDATAREQ_parametersETDATA.getItem().addAll(_siZMMMATERIALDATAREQ_parametersETDATAItem);
        _siZMMMATERIALDATAREQ_parameters.setETDATA(_siZMMMATERIALDATAREQ_parametersETDATA);
        com.chinaredstar.product.dubbo.sap.goods.ZMMMATERIALDATAResponse _siZMMMATERIALDATAREQ__return = port.siZMMMATERIALDATAREQ(_siZMMMATERIALDATAREQ_parameters);
        System.out.println("siZMMMATERIALDATAREQ.result=" + _siZMMMATERIALDATAREQ__return);


        }

        System.exit(0);
    }

}
