package com.chinaredstar.product.dubbo.sap.goods.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-08-21T15:21:37.803+08:00
 * Generated source version: 3.1.16
 * 
 */
@WebServiceClient(name = "SI_ZMM_MATERIAL_DATA_REQService", 
                  wsdlLocation = "file:/D:/work/proj/future-mmall/ws-client/sap08.wsdl",
                  targetNamespace = "http://chinaredstar.com/ecc2zt") 
public class SIZMMMATERIALDATAREQService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://chinaredstar.com/ecc2zt", "SI_ZMM_MATERIAL_DATA_REQService");
    public final static QName HTTPSPort = new QName("http://chinaredstar.com/ecc2zt", "HTTPS_Port");
    public final static QName HTTPPort = new QName("http://chinaredstar.com/ecc2zt", "HTTP_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/work/proj/future-mmall/ws-client/sap08.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SIZMMMATERIALDATAREQService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/work/proj/future-mmall/ws-client/sap08.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SIZMMMATERIALDATAREQService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIZMMMATERIALDATAREQService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZMMMATERIALDATAREQService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SIZMMMATERIALDATAREQService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SIZMMMATERIALDATAREQService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SIZMMMATERIALDATAREQService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SIZMMMATERIALDATAREQ
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZMMMATERIALDATAREQ getHTTPSPort() {
        return super.getPort(HTTPSPort, SIZMMMATERIALDATAREQ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZMMMATERIALDATAREQ
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZMMMATERIALDATAREQ getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SIZMMMATERIALDATAREQ.class, features);
    }


    /**
     *
     * @return
     *     returns SIZMMMATERIALDATAREQ
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZMMMATERIALDATAREQ getHTTPPort() {
        return super.getPort(HTTPPort, SIZMMMATERIALDATAREQ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZMMMATERIALDATAREQ
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZMMMATERIALDATAREQ getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SIZMMMATERIALDATAREQ.class, features);
    }

}
